package hluwa.dex.base;

public enum debug_opcode {
	DBG_END_SEQUENCE,
	DBG_ADVANCE_PC,
	DBG_ADVANCE_LINE,
	DBG_START_LOCAL,
	DBG_START_LOCAL_EXTENDED,
	DBG_END_LOCAL,
	DBG_RESTART_LOCAL,
	DBG_SET_PROLOGUE_END,
	DBG_SET_EPILOGUE_BEGIN,
	DBG_SET_FILE,
	DBG_UNKNOW;
}
